on:
  workflow_dispatch:

jobs:
  build:
    # Allow the job to fetch a GitHub ID token
    permissions:
      id-token: 'write'
      contents: 'read'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/112258718112/locations/global/workloadIdentityPools/github-pool/providers/github'
          service_account: 'ogg-sa@oggh-440221.iam.gserviceaccount.com'
          access_token_lifetime: '300s'
          # token_format: 'access_token'
          # export_environment_variables: true

      # - name: 'Install Google Cloud SDK'
      #   uses: 'google-github-actions/setup-gcloud@v1'

      - name: ''
        run: |
          gcloud auth login --cred-file="$GOOGLE_APPLICATION_CREDENTIALS"

      - name: 'Run BigQuery SQL Query'
        run: |
          bq query --use_legacy_sql=false 'select current_date() as today;'

      # - name: Run BigQuery Query
      #   run: |
      #     bq query --use_legacy_sql=false 'SELECT CURRENT_DATE() AS today;'

      # - name: Print message every second for 10 seconds
      #   run: |
      #     for i in {1..10}; do
      #       echo "This is message $i"
      #       sleep 1
      #     done