on:
  workflow_dispatch:

jobs:
  build:
    # Allow the job to fetch a GitHub ID token
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/112258718112/locations/global/workloadIdentityPools/github-pool/providers/github'
          service_account: 'ogg-sa@oggh-440221.iam.gserviceaccount.com'